'use client';

import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import Link from 'next/link';
import { profileRows, type Analysis, type Row } from '../../lib/omind-engine';

const API_BASE = process.env.NEXT_PUBLIC_OMIND_API_URL?.replace(/\/$/, '');
const ROLES: Record<string,string> = { manager:'مدیر', sales:'فروش', finance:'مالی', hr:'منابع انسانی', ops:'عملیات' };

type Session = { id:string; file:string; question:string; analysis:Analysis; createdAt:string };
type Decision = { id:string; problem:string; decision:string; expected_outcome:string; status:string; actual_outcome?:string|null; lesson?:string|null; created_at:string };

async function localParse(file:File):Promise<Row[]> { const buffer=await file.arrayBuffer(); const name=file.name.toLowerCase(); if(name.endsWith('.json')){const parsed=JSON.parse(new TextDecoder().decode(buffer));const rows=Array.isArray(parsed)?parsed:parsed?.data;if(!Array.isArray(rows)) throw new Error('JSON باید آرایه‌ای از objectها یا دارای data باشد.');return rows;} const wb=XLSX.read(buffer,{type:'array',cellDates:true});if(!wb.SheetNames.length) throw new Error('sheet قابل تحلیل وجود ندارد.');return XLSX.utils.sheet_to_json<Row>(wb.Sheets[wb.SheetNames[0]],{defval:null,raw:true}); }

export default function AppHome(){
 const [file,setFile]=useState<File|null>(null);const [role,setRole]=useState('manager');const [question,setQuestion]=useState('');const [analysis,setAnalysis]=useState<Analysis|null>(null);const [sessions,setSessions]=useState<Session[]>([]);const [decisions,setDecisions]=useState<Decision[]>([]);const [remaining,setRemaining]=useState(3);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [token,setToken]=useState('');const [workspaceId,setWorkspaceId]=useState('');const [userName,setUserName]=useState('');
 useEffect(()=>{const boot=async()=>{const t=localStorage.getItem('omind-session-token')||localStorage.getItem('omind-workspace-token')||'';const w=localStorage.getItem('omind-workspace-id')||'';if(!t||!w){window.location.href='/login';return;}setToken(t);setWorkspaceId(w);if(!API_BASE)return;try{const h={Authorization:`Bearer ${t}`};const [me,ws,as,ds]=await Promise.all([fetch(`${API_BASE}/auth/me`,{headers:h}),fetch(`${API_BASE}/workspaces/${w}`,{headers:h}),fetch(`${API_BASE}/workspaces/${w}/analyses`,{headers:h}),fetch(`${API_BASE}/decisions?workspace_id=${w}`,{headers:h})]);if(!me.ok){localStorage.removeItem('omind-session-token');window.location.href='/login';return;}const md=await me.json();setUserName(md.user.name);if(ws.ok){const x=await ws.json();setRemaining(x.remaining);}if(as.ok){const x=await as.json();setSessions(x.map((i:any)=>({id:i.id,file:i.filename,question:i.question,analysis:i.result,createdAt:new Date(i.created_at).toLocaleString('fa-IR')})));}if(ds.ok)setDecisions(await ds.json());}catch{setError('ارتباط با سرویس برقرار نشد.');}};void boot();},[]);
 const currentPersona=useMemo(()=>file?.name.toLowerCase().endsWith('.xlsx')||file?.name.toLowerCase().endsWith('.xls')?'Excel':file?.name.toLowerCase().endsWith('.json')?'JSON':'CSV',[file]);
 async function analyze(){if(!file)return setError('ابتدا فایل را انتخاب کن.');setBusy(true);setError('');try{if(!API_BASE){const rows=await localParse(file);const result=profileRows(rows,question,role);setAnalysis(result);setRemaining(v=>Math.max(0,v-1));return;}const body=new FormData();body.append('file',file);body.append('question',question);body.append('role',role);body.append('workspace_id',workspaceId);const r=await fetch(`${API_BASE}/analyses`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const data=await r.json();if(!r.ok)throw new Error(data.detail||'تحلیل ناموفق بود.');setAnalysis(data.result);setRemaining(v=>Math.max(0,v-1));setSessions(v=>[{id:data.id,file:data.filename,question:data.question,analysis:data.result,createdAt:new Date(data.created_at).toLocaleString('fa-IR')},...v]);}catch(c){setError(c instanceof Error?c.message:'تحلیل ناموفق بود.');}finally{setBusy(false);}}
 const signOut=()=>{localStorage.removeItem('omind-session-token');localStorage.removeItem('omind-workspace-token');localStorage.removeItem('omind-workspace-id');window.location.href='/';};
 return <main className="product-shell"><header className="app-nav"><Link href="/" className="wordmark"><span>O</span><strong>OMIND</strong></Link><nav><a className="active">Workspace</a><a href="#history">تاریخچه</a><a href="#decisions">Decision Memory</a></nav><div className="app-user"><span>{userName||'Workspace'}</span><b>{remaining}</b><button onClick={signOut}>خروج</button></div></header>
 <div className="app-layout"><aside className="app-sidebar"><div className="side-title">WORKSPACE</div><a className="side-active">⌁ تحلیل جدید</a><a href="#history">◷ تحلیل‌ها</a><a href="#decisions">◎ تصمیم‌ها</a><a href="#pricing">◇ پلن</a><div className="side-bottom"><small>PLAN</small><strong>{remaining} تحلیل باقی‌مانده</strong><div className="quota-bar"><i style={{width:`${Math.max(0,(remaining/3)*100)}%`}} /></div></div></aside>
 <section className="workspace-main"><div className="workspace-title"><div><small>GOOD MORNING{userName?` · ${userName}`:''}</small><h1>امروز چه چیزی را باید بفهمیم؟</h1><p>داده را وارد کن. OMIND مسئله مهم، شواهد و اقدام بعدی را پیدا می‌کند.</p></div><span className="live-pill"><i/> Engine ready</span></div>
 <div className="ingest-card"><div className="ingest-head"><div><small>01 · INGEST</small><h2>داده‌ات را وارد کن</h2></div><span className="file-badge">{file?currentPersona:'CSV · XLSX · JSON'}</span></div><label className="drop-area"><input type="file" accept=".csv,.xlsx,.xls,.json" onChange={e=>setFile(e.target.files?.[0]||null)} /><div className="drop-icon">↥</div><strong>{file?file.name:'فایل را اینجا رها کن یا انتخاب کن'}</strong><span>{file?`${currentPersona} آماده تحلیل است`:'حداکثر فایل مطابق محدودیت workspace'}</span></label><div className="analysis-controls"><label><span>نقش شما</span><select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(ROLES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="question-field"><span>سؤال اختیاری</span><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="مثلاً چرا فروش این ماه افت کرده؟" /></label></div><button className="primary analyze-button" onClick={analyze} disabled={busy||!file||remaining<=0}>{busy?'در حال تحلیل و اعتبارسنجی…':remaining<=0?'ارتقا برای تحلیل بیشتر':'شروع تحلیل ←'}</button>{error&&<div className="form-error">{error}</div>}</div>
 {analysis&&<AnalysisPanel analysis={analysis} />}
 <section id="history" className="app-section"><div className="section-line"><div><small>ANALYSIS MEMORY</small><h2>تحلیل‌های اخیر</h2></div><span>{sessions.length} session</span></div>{sessions.length?<div className="history-list">{sessions.slice(0,5).map(s=><button key={s.id} onClick={()=>setAnalysis(s.analysis)}><span>{s.file}</span><b>{s.question}</b><small>{s.createdAt}</small></button>)}</div>:<div className="empty-state">هنوز تحلیلی ثبت نشده است.</div>}</section>
 <section id="decisions" className="app-section"><div className="section-line"><div><small>DECISION MEMORY</small><h2>تصمیم‌هایی که باید نتیجه‌شان را ببینیم</h2></div><span>{decisions.length} decision</span></div>{decisions.length?<div className="decision-list">{decisions.slice(0,4).map(d=><div key={d.id}><span className={`status status-${d.status}`}>{d.status}</span><div><b>{d.decision}</b><small>{d.problem}</small></div></div>)}</div>:<div className="empty-state">اولین تحلیل را به یک تصمیم قابل پیگیری تبدیل کن.</div>}</section>
 </section></div></main>
}

function AnalysisPanel({analysis}:{analysis:Analysis}){return <section className="analysis-result"><div className="result-hero"><div><small>02 · SIGNAL</small><h2>{analysis.priorities[0]||'سیگنال مهمی پیدا نشد'}</h2><p>{analysis.hypotheses[0]||'برای اولویت‌بندی به شواهد بیشتر نیاز است.'}</p></div><div className="confidence"><b>{analysis.confidence}%</b><small>CONFIDENCE</small></div></div><div className="signal-grid"><div className="result-panel"><small>WHAT MATTERS</small>{analysis.signals.slice(0,3).map(s=><div className="signal-row" key={s.title}><span className={`priority priority-${s.priority}`}>{s.priority}</span><div><b>{s.title}</b><p>{s.detail}</p></div></div>)}</div><div className="result-panel action-panel"><small>NEXT ACTION</small>{analysis.actions.slice(0,3).map((a,i)=><div className="action-row" key={a}><i>{String(i+1).padStart(2,'0')}</i><span>{a}</span></div>)}<div className="trace-mini"><span>12 modules</span><span>evidence-first</span><span>outcome loop</span></div></div></div><details className="trace-details"><summary>ردیابی reasoning را ببین</summary><div className="trace-grid">{analysis.reasoning.steps.map(step=><div key={step.trace}><span>{step.trace}</span><b>{step.confidence}%</b><p>{step.output[0]}</p></div>)}</div></details></section>}
