'use client';

import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { profileRows, type Analysis, type Row } from '../lib/omind-engine';

const tabs = ['workspace', 'history', 'pricing'] as const;
type Tab = typeof tabs[number];
type FilePersona = { key: string; label: string; icon: string; accent: string; message: string };
type Session = { id: string; file: string; question: string; analysis: Analysis; createdAt: string };

const PERSONAS: Record<string, FilePersona> = {
  excel: { key: 'excel', label: 'Excel', icon: '▦', accent: '#21A366', message: 'اکسل را گرفتم. بگذار ببینم چه چیزی در جدول پنهان شده.' },
  csv: { key: 'csv', label: 'CSV', icon: '≡', accent: '#4F8EF7', message: 'داده خام رسید. ساختارش را بررسی می‌کنم.' },
  json: { key: 'json', label: 'JSON', icon: '{}', accent: '#F2C94C', message: 'ساختار JSON را بررسی می‌کنم و نقش فیلدها را درمی‌آورم.' },
  default: { key: 'default', label: 'OMIND', icon: 'O', accent: '#64A9FF', message: 'من آماده‌ام. داده را بده تا از مشاهده به تصمیم برویم.' },
};
function personaFor(name?: string) { const n = (name ?? '').toLowerCase(); if (n.endsWith('.xlsx') || n.endsWith('.xls')) return PERSONAS.excel; if (n.endsWith('.csv')) return PERSONAS.csv; if (n.endsWith('.json')) return PERSONAS.json; return PERSONAS.default; }

async function parseFile(file: File): Promise<Row[]> {
  const buffer = await file.arrayBuffer(); const name = file.name.toLowerCase();
  if (name.endsWith('.json')) { const parsed = JSON.parse(new TextDecoder().decode(buffer)); return Array.isArray(parsed) ? parsed : (parsed.data ?? []); }
  const workbook = XLSX.read(buffer, { type: 'array', cellDates: true }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; return XLSX.utils.sheet_to_json<Row>(sheet, { defval: null, raw: true });
}

export default function Home() {
  const [tab, setTab] = useState<Tab>('workspace'); const [file, setFile] = useState<File | null>(null); const [role, setRole] = useState('manager'); const [question, setQuestion] = useState(''); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const remaining = Math.max(0, 3 - sessions.length); const roleLabel = useMemo(() => ({ manager: 'مدیر', sales: 'فروش', finance: 'مالی', hr: 'منابع انسانی', ops: 'عملیات' }[role] ?? 'مدیر'), [role]); const persona = useMemo(() => personaFor(file?.name), [file?.name]);
  async function analyze() { if (!file) return setError('ابتدا یک فایل CSV، XLSX، XLS یا JSON انتخاب کن.'); if (remaining === 0) return setError('سهمیه نسخه آزمایشی تمام شده است.'); setBusy(true); setError(''); try { const rows = await parseFile(file); if (!rows.length) throw new Error('فایل داده قابل تحلیل ندارد.'); const seed = profileRows(rows); const q = question.trim() || seed.questions[0] || 'مهم‌ترین مسئله این داده چیست؟'; const result = profileRows(rows, q); const session = { id: crypto.randomUUID(), file: file.name, question: q, analysis: result, createdAt: new Date().toLocaleString('fa-IR') }; setAnalysis(result); setQuestion(q); setSessions(prev => [session, ...prev]); } catch (e) { setError(e instanceof Error ? e.message : 'خواندن فایل ناموفق بود.'); } finally { setBusy(false); } }
  function selectFile(next: File | null) { setFile(next); setAnalysis(null); setError(''); } function reset() { setFile(null); setAnalysis(null); setQuestion(''); setError(''); }
  return <main className="app-shell" style={{ '--persona-accent': persona.accent } as React.CSSProperties}>
    <header className="topbar"><button className="brand" onClick={() => setTab('workspace')} aria-label="OMIND home"><span className="brand-mark">O</span><span><strong>OMIND</strong><small>DATA → DECISION</small></span></button><nav>{tabs.map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t === 'workspace' ? 'تحلیل‌گر' : t === 'history' ? 'حافظه تصمیم' : 'قیمت'}</button>)}</nav><div className="quota"><span>FREE</span><b>{remaining}</b><small>تحلیل</small></div></header>
    {tab === 'workspace' && <section className="workspace-page">
      <div className="hero-row"><div className="hero-copy"><span className="eyebrow">INTELLIGENCE FOR REAL BUSINESS DATA</span><h1>فایل را بده.<br /><em>مسئله را پیدا کن.</em><br />اقدام بعدی را بگیر.</h1><p>OMIND داده را پروفایل می‌کند، کیفیت و سیگنال‌های مهم را پیدا می‌کند و تحلیل را به سؤال، اولویت و اقدام تبدیل می‌کند.</p><div className="proof"><span>۳ تحلیل رایگان</span><span>Excel · CSV · JSON</span><span>شفاف و قابل ردیابی</span></div></div><OmindAgent persona={persona} busy={busy} analysis={!!analysis} /></div>
      <div className="workspace-grid"><div className="panel main-panel"><div className="panel-head"><div><span className="eyebrow">01 / INGEST</span><h2>داده‌ات را وارد کن</h2></div><button className="ghost" onClick={reset}>پاک کردن</button></div><label className="dropzone" data-persona={persona.key}><input type="file" accept=".csv,.xlsx,.xls,.json" onChange={e => selectFile(e.target.files?.[0] ?? null)} /><span className="upload-icon">↑</span><strong>{file ? file.name : 'فایل را اینجا بکش یا انتخاب کن'}</strong><small>CSV · XLSX · XLS · JSON — پردازش نمونه فعلاً داخل مرورگر انجام می‌شود.</small></label><div className="agent-status"><span className="status-dot" /><b>{persona.label}</b><span>{persona.message}</span></div><div className="controls"><label>نقش شما<select value={role} onChange={e => setRole(e.target.value)}><option value="manager">مدیر</option><option value="sales">فروش</option><option value="finance">مالی</option><option value="hr">منابع انسانی</option><option value="ops">عملیات</option></select></label><label className="wide">سؤال یا هدف تحلیل<textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder={`مثلاً: مهم‌ترین مسئله ${roleLabel} در این داده چیست؟`} rows={3} /></label></div>{analysis && <div className="question-list"><span className="eyebrow">QUESTIONS</span>{analysis.questions.map(q => <button key={q} onClick={() => setQuestion(q)}>{q}</button>)}</div>}{error && <div className="error">{error}</div>}<button className="primary full" onClick={analyze} disabled={busy || remaining === 0}>{busy ? 'در حال تحلیل…' : 'اجرای تحلیل ←'}</button></div>
        <aside className="panel engine-panel"><span className="eyebrow">OMIND ENGINE</span><h3>از داده تا تصمیم</h3><div className="pipeline">{['Intake','Observe','Decompose','Pattern','Hypothesis','Causality','Decision','Scenarios','Experiment','Action','Feedback','Loop'].map((x, i) => <div key={x}><i>{String(i + 1).padStart(2, '0')}</i><span>{x}</span></div>)}</div><p>هسته تحلیل deterministic و قابل توضیح است؛ مدل زبانی بعداً به‌عنوان لایه تقویتی به آن متصل می‌شود.</p></aside></div></section>}
    {tab === 'workspace' && analysis && <AnalysisView analysis={analysis} question={question} />}
    {tab === 'history' && <section className="content-page"><span className="eyebrow">DECISION MEMORY</span><h1>حافظه تحلیل‌ها</h1><p>در این مرحله تاریخچه داخل همین session نگهداری می‌شود؛ persistence سمت سرور در لایه بعدی اضافه خواهد شد.</p>{sessions.length ? sessions.map(s => <article className="history-card" key={s.id}><div><b>{s.file}</b><small>{s.createdAt}</small></div><h3>{s.question}</h3><span>Health {s.analysis.health}/100 · Confidence {s.analysis.confidence}%</span></article>) : <div className="empty">هنوز تحلیلی اجرا نشده.</div>}</section>}
    {tab === 'pricing' && <section className="content-page pricing-page"><span className="eyebrow">PAY WHEN VALUE IS PROVEN</span><h1>سه تحلیل را رایگان امتحان کن.</h1><div className="prices"><Price title="تحلیل تکی" price="۳۹۰٬۰۰۰" detail="یک تحلیل کامل فایل"/><Price title="Pro" price="۲٬۴۹۰٬۰۰۰" detail="۳۰ تحلیل + حافظه" featured/><Price title="Team" price="۶٬۹۰۰٬۰۰۰" detail="تا ۱۰ کاربر + فضای تیمی"/></div></section>}
  </main>;
}

function OmindAgent({ persona, busy, analysis }: { persona: FilePersona; busy: boolean; analysis: boolean }) { return <div className={`agent-wrap ${busy ? 'thinking' : ''} ${analysis ? 'success' : ''}`} aria-label="OMIND agent"><div className="agent-bubble" style={{ borderColor: persona.accent }}><span>{busy ? 'در حال فکر…' : persona.message}</span></div><div className="agent-avatar" style={{ '--agent-color': persona.accent } as React.CSSProperties}><div className="agent-aura" /><div className="agent-body"><span className="tie" /></div><div className="agent-head"><span className="ear left"/><span className="ear right"/><span className="face"/><span className="glasses"><i/><i/></span><span className="beard"/><span className="nose"/><span className="mouth"/></div><div className="agent-badge">{persona.icon}</div></div><div className="agent-label"><b>OMIND Agent</b><span>{persona.label}</span></div></div>; }

function AnalysisView({ analysis, question }: { analysis: Analysis; question: string }) { return <section className="analysis-section"><div className="result-header"><div><span className="eyebrow">DECISION ROOM</span><h2>{question}</h2></div><div className="score"><b>{analysis.health}</b><span>DATA HEALTH</span></div></div><div className="metric-grid"><Metric label="ردیف" value={analysis.rows.toLocaleString('fa-IR')} /><Metric label="ستون" value={analysis.columns.length.toLocaleString('fa-IR')} /><Metric label="سیگنال" value={analysis.signals.length.toLocaleString('fa-IR')} /><Metric label="Confidence" value={`${analysis.confidence}%`} /></div><div className="result-grid"><ResultCard title="Key Signals">{analysis.signals.length ? analysis.signals.map(s => <div className="signal" key={s.title}><span className={`priority ${s.priority}`}>{s.priority === 'high' ? 'HIGH' : s.priority === 'medium' ? 'MED' : 'LOW'}</span><div><b>{s.title}</b><p>{s.detail}</p></div></div>) : <p>سیگنال قابل توجهی با قواعد فعلی شناسایی نشد.</p>}</ResultCard><ResultCard title="Top Priorities">{analysis.priorities.map(x => <p className="bullet" key={x}>{x}</p>)}</ResultCard><ResultCard title="Hypotheses">{analysis.hypotheses.map(x => <p className="hypothesis" key={x}>{x}</p>)}</ResultCard><ResultCard title="Recommended Actions">{analysis.actions.map((x, i) => <p className="action" key={x}><b>{i + 1}</b>{x}</p>)}</ResultCard></div><details className="trace"><summary>Reasoning Trace — 12 modules</summary><div>{analysis.trace.map(x => <span key={x}>{x}</span>)}</div></details><details className="trace reasoning-detail"><summary>Execution Detail — confidence / outputs</summary><div>{analysis.reasoning.steps.map(step => <article key={step.module}><b>{step.module}</b><small>confidence {step.confidence}%</small>{step.output.map((out, i) => <p key={`${step.module}-${i}`}>{out}</p>)}</article>)}</div></details><div className="columns"><h3>Data Model</h3>{analysis.columns.map(c => <div key={c.name}><b>{c.name}</b><span>{c.role}</span><small>{c.type} · missing {c.missing}</small></div>)}</div></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><b>{value}</b></div>; }
function ResultCard({ title, children }: { title: string; children: React.ReactNode }) { return <article className="result-card"><span className="eyebrow">{title}</span><div>{children}</div></article>; }
function Price({ title, price, detail, featured = false }: { title: string; price: string; detail: string; featured?: boolean }) { return <article className={`price ${featured ? 'featured' : ''}`}><span>{title}</span><b>{price}</b><small>تومان / ماه</small><p>{detail}</p><button className={featured ? 'primary' : 'ghost'}>به‌زودی</button></article>; }
